CREATE TABLE EMP_TEMP2 AS SELECT * FROM EMP;

SELECT * FROM EMP_TEMP2;

--JOB이 MANAGER인 데이터 삭제(행단위 삭제)
DELETE FROM EMP_TEMP2 WHERE JOB = 'MANAGER';
--FROM, WHERE : 필수 X
DELETE EMP_TEMP2;

ROLLBACK;

--EMP_TEMP2 테이블 사원 중 급여가 5000이상인 사원 삭제
DELETE FROM EMP_TEMP2 WHERE SAL >= 5000;

COMMIT;

--실습1
--기존 테이블 복제
----EMP -> EXAM_EMP / DEPT -> EXAM_DEPT / SALGRADE -> EXAM_SALGRADE
CREATE TABLE EXAM_EMP AS SELECT * FROM EMP;
CREATE TABLE EXAM_DEPT AS SELECT * FROM DEPT;
CREATE TABLE EXAM_SALGRADE AS SELECT * FROM salgrade;

DESC EXAM_EMP;
ROLLBACK;

--실습2 : 테이블에 데이터 입력
INSERT INTO EXAM_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7201, 'TEST_USER1', 'MANAGER', 7788, '2016-01-02', 4500, NULL, 50);
INSERT INTO EXAM_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(7202, 'TEST_USER2', 'CLERK', 7201, '2016-02-21', 1800, NULL, 50);
INSERT INTO EXAM_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(7203, 'TEST_USER3', 'ANALYST', 7201, '2016-04-11', 3400, NULL, 60);
INSERT INTO EXAM_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(7204, 'TEST_USER4', 'SALESMAN', 7201, '2016-05-31', 2700, 300, 60);
INSERT INTO EXAM_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(7205, 'TEST_USER5', 'CLERK', 7201, '2016-07-20', 2600, NULL, 70);
INSERT INTO EXAM_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(7206, 'TEST_USER6', 'CLERK', 7201, '2016-09-08', 2600, NULL, 70);
INSERT INTO EXAM_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(7207, 'TEST_USER7', 'LECTURER', 7201, '2016-10-28', 2300, NULL, 80);
INSERT INTO EXAM_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(7208, 'TEST_USER8', 'STUDENT', 7201, '2018-03-09', 1200, NULL, 80);


ROLLBACK;
COMMIT;

--실습3
----EXAM_EMP에 속한 사원 중 50번 부서에서 근무하는 사원들의 평균 급여보다 많은 
UPDATE EXAM_EMP
SET DEPTNO = 70
WHERE SAL > (SELECT AVG(SAL) FROM EXAM_EMP WHERE DEPTNO = 50);



SELECT AVG(SAL) FROM EXAM_EMP WHERE DEPTNO = 50;

SELECT * FROM EXAM_EMP;

--실습4
----EXAM_EMP 사원 중 60번 부서 중 입사일이 가장 빠른 사원 보다 늦게 입사한 사원
----급여 10퍼 인상, 부서 이동(80번)
UPDATE EXAM_EMP
SET SAL=SAL*1.1, DEPTNO = 80
WHERE HIREDATE > (SELECT MIN(HIREDATE) FROM EXAM_EMP WHERE DEPTNO=60);


--급여 등급 3등급 사이에 있는 30번 부서 사원만 삭제
DELETE FROM EMP_TEMP2 WHERE EMPNO IN (SELECT E.EMPNO
                                                                      FROM EMP_TEMP2 E, SALGRADE S
                                                                      WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                                                                      AND S.GRADE =3 AND DEPTNO = 30);
ROLLBACK;



