CREATE TABLE DEPT_TEMP2 AS SELECT * FROM DEPT;

--DEPT_TEMP2에 있는 LOC 모두 수정
UPDATE DEPT_TEMP2 --테이블명
SET LOC='SEOUL';      --수정할 내용

SELECT * FROM DEPT_TEMP2;

ROLLBACK; --CTRL + Z

SELECT * FROM DEPT_TEMP2;

UPDATE DEPT_TEMP2 --테이블명
SET LOC='SEOUL'      --수정할 내용
WHERE DEPTNO = 10; --업데이트 조건

SELECT * FROM DEPT_TEMP2;

-- EMP_TEMP 테이블 사원들 중에 급여가 3000이하인 사원만 추가 수당을
--50으로 수정

UPDATE EMP_TEMP
SET COMM = 50
WHERE SAL <=3000;
----기존 커미션이 있다면
--UPDATE EMP_TEMP
--SET COMM = COMM + 50
--WHERE SAL <=3000;

SELECT * FROM EMP_TEMP;

--서브쿼리()를 이용한 데이터 수정

--40번 부서의 부서명과 지역 수정
SELECT * FROM DEPT_TEMP2;
UPDATE dept_temp2
SET (DNAME, LOC) = (SELECT DNAME, LOC FROM DEPT WHERE DEPTNO = 30)
WHERE DEPTNO = 40;

--
UPDATE dept_temp2
SET LOC = 'SEOUL'
WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME= 'OPERATIONS');
SELECT * FROM DEPT_TEMP2;

COMMIT;
